project:
  type: website
  output-dir: docs

website:
  title: "Cai Naidoo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Projects.qmd
        text: Projects

format:
  html:
    theme:
      light: flatly
      dark: darkly
    mainfont: Inter
    headingfont: Space Grotesk
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

