---
title: "My Website"
format: 
  html:
    css: style.css
---

This is a Quarto website.

Cai Naidoo
Finance - Data - Systems
Tracking Delta - Building projects that improve over time.

##Hi I am Cai!

I am a University of Alberta student interested in finance, data, algorithmic trading, and building systems that improve over time

##Background
My intial exposure to coding came in the form of game scripting where I used Lua to tweak small mechanics within game systems to automate them. That exposure reall taught me to think about how environments and rules can interact.

##What I am learning now
Recently I have been learning about Linux-Based environments outside of school and exploring new programming languages to help with algorithmic trading. I am currently attempting to learn **Ocaml**, to really push myself into new areas.

##Beyond just coding
Outside of coding and technical work I find myself enjoying gardening, running and speaking with new people with new ideas who bring all different kinds of strenghths to the table

##What Drives me and where I hope to be
What motivates me most is gaining new knowledge and being able to see the progress that is rewarded after finding solutions to problems I had prior. I am not sure exactly what specific area of finance I want to work in, however I am interested in always exploring new oppurtunities in different sectors!

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

```{r}
1 + 1
```
